### ISSUE TITLE
Adding a license

### ISSUE THREAD

**Issue by johanricher** [CityOfBoston/analytics_docs#1]
Thanks for publishing this documentation, this is an invaluable resource! Would you be willing to add the final touch with a license file, to make this truly open?

**Comment by JPHaus** [comment]
Thanks for the flag! I just added a CC0-1.0 License with [this commit](https://github.com/CityOfBoston/analytics_docs/commit/3b68eb528a0227aa831ec0b297a831873a6c21da).

**Comment by johanricher** [comment]
That's wonderful! Thanks for all of this Jonathan and congrats from France, I think this will be super useful for a lot of cities around the world.
